#!/bin/sh

for DIR in */
do

  cd $DIR
  if [ -e "test" ]; then
    
    echo "TESTING $DIR"
    if ! ./test; then
      echo "DFOJOGSDKNFGSDKNGSDKNGSDGNSDKLGNSDJNGSLDKNGSDKBGSDLNGSDNKg"
      exit 1
    fi

    echo ""
  fi
  cd ..

done
