#!/bin/sh
sh build
java -cp .:../junit-4.12.jar:../hamcrest-core-1.3.jar org.junit.runner.JUnitCore QueueTest
java -cp .:../junit-4.12.jar:../hamcrest-core-1.3.jar org.junit.runner.JUnitCore IntQueueTest
rm *.class 2> /dev/null
